version: '3.7'

services:
  postgres:
    image: postgres:16-alpine3.18
    restart: unless-stopped
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'
      PGDATA: /data/postgres
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    volumes:
      - psql_data:/data/postgres

  redis:
    image: redis:7.2-alpine3.18
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_cache:/data
      - ./data/redis:/data/redis

#  api:
#    image: server
#    build: ./server/
#    environment:
#      - PORT=${PORT}
#      - HOST=${HOST}
#      - NODE_ENV=${NODE_ENV}
#      - APP_KEY=${APP_KEY}
#      - LOG_LEVEL=${LOG_LEVEL}
#      - TZ=${TZ}
#      - CACHE_VIEWS=${CACHE_VIEWS}
#
#      - COOKIE_DOMAIN=${COOKIE_DOMAIN}
#      - CORS_ORIGIN=${CORS_ORIGIN}
#
#      - DB_CONNECTION=${DB_CONNECTION}
#
#      - PG_HOST=${DB_HOST}
#      - PG_PORT=${DB_PORT}
#      - PG_USER=$DB_USER}
#      - PG_PASSWORD=${DB_PASSWORD}
#      - PG_DB_NAME=${DB_DATABASE}
#
#      - SESSION_DRIVER=${SESSION_DRIVER}
#
#      - REDIS_CONNECTION=${REDIS_CONNECTION}
#      - REDIS_HOST=${REDIS_HOST}
#      - REDIS_PORT=${REDIS_PORT}
#      - REDIS_PASSWORD=${REDIS_PASSWORD}
#    depends_on:
#      - postgres
#      - redis


volumes:
  psql_data:
  redis_cache:
