version: '3.7'

services:
  postgres:
    image: postgres:16-alpine3.18
    restart: unless-stopped
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'
      PGDATA: /data/postgres
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    volumes:
      - psql_data:/data/postgres

  redis:
    image: redis:7.2-alpine3.18
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_cache:/data
      - ./data/redis:/data/redis

  adonis:
    image: rpg-server
    build: ./
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .env:/app/.env
    depends_on:
      - postgres
      - redis

volumes:
  psql_data:
  redis_cache:
